

SEED = 6687651975
YFINANCE_COLUMNS = ["Open", "High", "Low", "Close", "Adj Close", "Volume"]

YFINANCE_CORRELATION_COLUMNS = ["H/L Mean", "O/C Mean"]

CORRELATION_TOLERANCE = .75
INVERSE_CORRELATION_TOLERANCE = CORRELATION_TOLERANCE * -1.0
